### ISSUE TITLE
Adopt test as you commit policy?

### ISSUE THREAD

**Issue by anssiko** [w3c/secondscreen-charter#2]
Do we want to adopt test as you commit policy? Proposed text to be added to the Deliverables section similarly to [DAS WG](https://w3c.github.io/dap-charter/DeviceAPICharter.html#deliverables):

>The Second Screen Working Group will follow a [test as you commit](https://github.com/w3c/testing-how-to/#test-as-you-commit) approach to specification development, for specifications in CR or above.

@tidoust @mfoltzgoogle for comments.

**Comment by tidoust** [comment]
And you wanted to keep changes minimal ;)

Similar text is indeed recommended in new WG. We did not discuss it at the F2F, so I did introduce that change in the charter. I'm not particularly worried about testing in the Second Screen WG, the group seems to be handling it quite fine already without policy. That said, I'm certainly fine with it, so happy to add such text to the charter.

**Comment by anssiko** [comment]
I had planned to bring this topic to the F2F agenda, but it slipped through the cracks -- my bad. Testing was a big theme at TPAC this year so many folks got exposure to the topic nevertheless.

@mfoltzgoogle any concerns from your side in adding a mention of "test as you commit" policy to the Charter 2018? We do not necessarily need to bake this into the charter for the group to do the right thing, but this would follow the best practice.

**Comment by mfoltzgoogle** [comment]
SGTM
