### ISSUE TITLE
no mandatory-to-implement codecs?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/secondscreen-charter#24]
I'm surprised by the charter constraint of "This Working Group will not ... mandate any video or audio codecs."

Can we get robust Web-style interop without that?

**Comment by mfoltzgoogle** [comment]
Basically what @tidoust said.  The APIs and protocols will interoperate, but not guarantee that specific content on one device can be presented successfully on another.

**Comment by tidoust** [comment]
Closing. No change made to the charter approved early 2022 and no change of approach planned for the upcoming charter.
