### ISSUE TITLE
authorization missing?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/secondscreen-charter#25]
The charter mentions authentication, but without quite giving me enough context to understand what features might require authentication, and how.  I'm surprised then, that authorization is not also in scope.  

Could someone summarize (here) how authentication and authorization are being done in the implementations to date?

**Comment by tidoust** [comment]
@mfoltzgoogle, see above

**Comment by mfoltzgoogle** [comment]
"Authorization" in the most general sense requires one party or entity to grant a capability to another party to do something.  Currently we do not see a role for SSWG APIs to define additional content authorization schemes for the Web, as there are already solutions in place for this like Encrypted Media Extensions. The APIs and protocols give Web applications the tools they need to support EME content as has been demonstrated by adoption of the Presentation API by a variety of Cast applications that use EME.

Perhaps you meant something else by authorization.  Some specific scenarios might help us understand what you have in mind.

**Comment by tidoust** [comment]
Closing. No change made to the charter approved early 2022 and no change planned for the next iteration either.
