### ISSUE TITLE
Presentation API

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/secondscreen-charter#3]
Under Normative Specifications for the Presentation API,  we propose that progress on the Presentation API depend on exit criteria and implementation status, not the Open Screen Protocol directly, as (1) it is out of scope for the charter, and (2) it prevents non-Open-Screen implementations from meeting the exit criteria.

Suggested changes:

> That said, known implementation plans are tied to the availability of the Open Screen Protocol, under incubation in the Second Screen Community Group.  The Working Group does not expect to be able to meet the Success Criteria for the Presentation API in the meantime.

be amended to

> The Working Group is awaiting the satisfaction of the exit criteria, which require two interoperable implementations of the Presentation API.   The Open Screen Protocol under incubation in the Second Screen Working Group is one proposed basis for interoperability, and implementations based on it would satisfy those criteria.  The charter timeline provides additional time for interoperable implementations to be completed.

We also suggest:

> This Working Group plans to assess progress on the suite of protocols at the end of this Charter.

be amended to

> This Working Group plans to assess progress on interoperability and implementation status regularly.

We also suggest:

> ...to request re-chartering accordingly to finalize the specification.

be amended to:

> ...to request re-chartering according to progress on meeting exit criteria.

**Comment by tidoust** [comment]
As commented on PR #7, I was not trying to introduce a "dependency", but suggested changes look good in any case!
