### ISSUE TITLE
Remote Playback API

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/secondscreen-charter#4]
Unless I'm mistaken, no implementation has shown any signal of supporting the Remote Playback API via the Open Screen Protocol and no concrete proposals have been submitted to the CG on how the protocol would work.  In light of that, the reference to it in the status for the Remote Playback API is somewhat confusing.

It would be fine to refer to future plans to support Remote Playback via the Open Screen Protocol in the Dependencies/Liasons section, but it is not currently required to meet exit criteria for the spec.

Suggest:

> As for the Presentation API, progress on the Open Screen Protocol will benefit this specification, but this Working Group still expects to publish the Remote Playback API as a final Recommendation in parallel to protocol discussions.

be amended to:

> The Working Group plans to publish the Remote Playback API as a final Recommendation when two interoperable implementations are provided that meet the exit criteria.

**Comment by tidoust** [comment]
OK, actually my goal was to say "Progress on the Presentation API may be delayed, but progress on the Remote Playback API should not be impacted by the Open Screen Protocol", but there's no real need to be pro-active in the charter about that, so fine with dropping that text.
